### ISSUE TITLE
Requested Windows Runtime type 'Sqlite.Sqlite3' 

### ISSUE THREAD

**Issue by shadrix** [peterhuene/sqlite-net-wp8#13]
I publish windows phone 8 app to store, and a lot of users not have trouble with him, but some time i get this error and i don't know why. 

System.TypeLoadException: Requested Windows Runtime type 'Sqlite.Sqlite3' is not registered. ---> System.Runtime.InteropServices.COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   --- End of inner exception stack trace ---
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Sqlite.Sqlite3.sqlite3_open_v2(String filename, Database& db, Int32 flags, String zVfs)
   at SQLite.SQLiteConnection..ctor(String databasePath, SQLiteOpenFlags openFlags, Boolean storeDateTimeAsTicks)
   at SQLite.SQLiteConnectionWithLock..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnectionPool.Entry..ctor(SQLiteConnectionString connectionString)
   at SQLite.SQLiteConnectionPool.GetConnection(SQLiteConnectionString connectionString)
   at SQLite.SQLiteAsyncConnection.Table[T]()
   at CraigsList.DataAccess.Providers.LocalDataProvider.<TakeLocations>d__2f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at 

Anybody know how fix this?!)

**Comment by peterhuene** [comment]
Are you sure the target architectures match between the project you're building and the Sqlite project?  Make sure it targets ARM for the phone deployment and x86 for the emulator.

**Comment by shadrix** [comment]
I'm sure.

**Comment by peterhuene** [comment]
Is this being run on the emulator or on a device?  Was Sqlite.dll renamed for deployment by chance?

**Comment by peterhuene** [comment]
Were you ever able to figure this issue out?
