### ISSUE TITLE
UpdateAll Exception

### ISSUE THREAD

**Issue by Grunt101** [peterhuene/sqlite-net-wp8#38]
Hi,

I recently updated the solution to the latest version of Sqlite-Net-WP8, but now I see that whenever I try to call UpdateAll, I get the following exception : 

{SQLite.SQLiteException: SQL logic error or missing database
   at SQLite.SQLiteConnection.Update(Object obj, Type objType)
   at SQLite.SQLiteConnection.Update(Object obj)
   at SQLite.SQLiteConnection.<>c__DisplayClass17.<UpdateAll>b__16()
   at SQLite.SQLiteConnection.RunInTransaction(Action action)
   at SQLite.SQLiteConnection.UpdateAll(IEnumerable objects)

This used to work in the previous version I had, so not sure what is different?

Thanks

**Comment by gregdickie** [comment]
Hi Grunt101,

I'm having the same problem now in my code after updating. Were you ever able to figure out what the problem was?

Thanks

**Comment by Grunt101** [comment]
Hey Greg,

Yip, I did eventually find the fix. It has to do with setting the temp directory for SQLIite to use. Try executing this query before you do any DB interactions.

sqLiteConnection.Execute("PRAGMA temp_store_directory = '" + DATABASE_LOCATION + "'"); 

It should then fix the issue above. 

Hope it helps you out

Cheers

**Comment by gregdickie** [comment]
Thanks Grunt101, I’ll give that a try.

Greg
